import type {
  CreateFolhaPagamentoRequest,
  ExecutarFolhaPagamentoRequest,
  FolhaPagamentoExecucaoRow,
  FolhaPagamentoPessoaLogRow,
  FolhaPagamentoRow,
  FolhaPagamentoRubricaLogRow,
  UpdateFolhaPagamentoRequest,
} from "./types";

const folhasPagamentoMock: FolhaPagamentoRow[] = [
  {
    id: 1,
    numero: "2026-05-NORMAL",
    nome: "Folha Normal Maio/2026",
    mesAnoReferencia: "2026-05",
    competencia: "2026-05",
    observacao: "Processamento mensal da folha normal.",
    orgaos: ["SEPLAG", "MTI"],
    regimeJuridico: "Estatutário Civil",
    categoria: "Área Meio",
    cargo: "",
    grupoEleitos: "",
    totalMesesAdiantar: 0,
    totalMesesRetroagir: 1,
    situacao: "ABERTA",
    totalPessoas: 842,
    totalSucesso: 0,
    totalAlerta: 0,
    totalErro: 0,
    ultimaExecucao: "-",
  },
  {
    id: 2,
    numero: "2026-05-EDU",
    nome: "Folha Educação Maio/2026",
    mesAnoReferencia: "2026-05",
    competencia: "2026-05",
    observacao: "Recorte de profissionais da educação.",
    orgaos: ["SEDUC"],
    regimeJuridico: "Estatutário Civil",
    categoria: "Profissionais da Educação",
    cargo: "Professor da Educação Básica",
    grupoEleitos: "",
    totalMesesAdiantar: 0,
    totalMesesRetroagir: 0,
    situacao: "EM_PROCESSAMENTO",
    totalPessoas: 12840,
    totalSucesso: 9200,
    totalAlerta: 84,
    totalErro: 12,
    ultimaExecucao: "28/05/2026 09:14",
  },
  {
    id: 3,
    numero: "2026-04-SAUDE",
    nome: "Folha Saúde Abril/2026",
    mesAnoReferencia: "2026-04",
    competencia: "2026-04",
    observacao: "Execução com alerta para conferência de adicionais.",
    orgaos: ["SES"],
    regimeJuridico: "Estatutário Civil",
    categoria: "Profissionais da Saúde",
    cargo: "Médico",
    grupoEleitos: "Grupo Teste",
    totalMesesAdiantar: 0,
    totalMesesRetroagir: 2,
    situacao: "PROCESSADA_COM_ALERTA",
    totalPessoas: 3120,
    totalSucesso: 3058,
    totalAlerta: 62,
    totalErro: 0,
    ultimaExecucao: "07/05/2026 17:48",
  },
  {
    id: 4,
    numero: "2026-05-RASC",
    nome: "Folha Complementar Maio/2026",
    mesAnoReferencia: "2026-05",
    competencia: "2026-05",
    observacao: "",
    orgaos: ["SEPLAG"],
    regimeJuridico: "",
    categoria: "",
    cargo: "",
    grupoEleitos: "PESSOA FÍSICA",
    totalMesesAdiantar: 1,
    totalMesesRetroagir: 0,
    situacao: "RASCUNHO",
    totalPessoas: 0,
    totalSucesso: 0,
    totalAlerta: 0,
    totalErro: 0,
    ultimaExecucao: "-",
  },
  {
    id: 5,
    numero: "2026-03-ERRO",
    nome: "Folha Especial Março/2026",
    mesAnoReferencia: "2026-03",
    competencia: "2026-03",
    observacao: "Execução encerrada com inconsistências.",
    orgaos: ["SAD"],
    regimeJuridico: "Contrato Temporário",
    categoria: "Área Meio",
    cargo: "Gestor Governamental",
    grupoEleitos: "",
    totalMesesAdiantar: 0,
    totalMesesRetroagir: 3,
    situacao: "PROCESSADA_COM_ERRO",
    totalPessoas: 460,
    totalSucesso: 430,
    totalAlerta: 11,
    totalErro: 19,
    ultimaExecucao: "04/04/2026 10:22",
  },
];

const folhasPagamentoExecucoesMock: FolhaPagamentoExecucaoRow[] = [
  {
    id: 1001,
    folhaPagamentoId: 2,
    situacao: "EM_PROCESSAMENTO",
    dataHoraInicio: "28/05/2026 09:14",
    dataHoraFim: "-",
    usuarioResponsavel: "ROBERTO JUNIOR",
    totalPessoas: 12840,
    totalSucesso: 9200,
    totalAlerta: 84,
    totalErro: 12,
    parametrosResumo: "Adiantar 0 mês(es), retroagir 0 mês(es)",
  },
  {
    id: 1002,
    folhaPagamentoId: 3,
    situacao: "CONCLUIDA_COM_ALERTA",
    dataHoraInicio: "07/05/2026 17:12",
    dataHoraFim: "07/05/2026 17:48",
    usuarioResponsavel: "ROBERTO JUNIOR",
    totalPessoas: 3120,
    totalSucesso: 3058,
    totalAlerta: 62,
    totalErro: 0,
    parametrosResumo: "Adiantar 0 mês(es), retroagir 2 mês(es)",
  },
  {
    id: 1003,
    folhaPagamentoId: 5,
    situacao: "CONCLUIDA_COM_ERRO",
    dataHoraInicio: "04/04/2026 09:51",
    dataHoraFim: "04/04/2026 10:22",
    usuarioResponsavel: "ROBERTO JUNIOR",
    totalPessoas: 460,
    totalSucesso: 430,
    totalAlerta: 11,
    totalErro: 19,
    parametrosResumo: "Adiantar 0 mês(es), retroagir 3 mês(es)",
  },
];

const folhasPagamentoPessoaLogsMock: FolhaPagamentoPessoaLogRow[] = [
  {
    id: 5001,
    execucaoId: 1002,
    matricula: "102938",
    vinculo: "1",
    nome: "ANA PAULA MARTINS",
    cpf: "123.456.789-09",
    orgao: "SES",
    regimeJuridico: "Estatutário Civil",
    categoria: "Profissionais da Saúde",
    cargo: "Médico",
    grupoEleitos: "Grupo Teste",
    situacao: "SUCESSO",
    mensagem: "Pessoa processada com sucesso.",
  },
  {
    id: 5002,
    execucaoId: 1002,
    matricula: "102939",
    vinculo: "2",
    nome: "BRUNO ALMEIDA COSTA",
    cpf: "987.654.321-00",
    orgao: "SES",
    regimeJuridico: "Estatutário Civil",
    categoria: "Profissionais da Saúde",
    cargo: "Médico",
    grupoEleitos: "Grupo Teste",
    situacao: "ALERTA",
    mensagem: "Adicional noturno calculado com divergência de referência.",
  },
  {
    id: 5003,
    execucaoId: 1003,
    matricula: "778899",
    vinculo: "1",
    nome: "CARLA SOUZA LIMA",
    cpf: "111.222.333-44",
    orgao: "SAD",
    regimeJuridico: "Contrato Temporário",
    categoria: "Área Meio",
    cargo: "Gestor Governamental",
    grupoEleitos: "",
    situacao: "ERRO",
    mensagem: "Rubrica 1002 sem parametrização vigente para a competência.",
  },
  {
    id: 5004,
    execucaoId: 1001,
    matricula: "445566",
    vinculo: "1",
    nome: "DIEGO RIBEIRO NUNES",
    cpf: "555.666.777-88",
    orgao: "SEDUC",
    regimeJuridico: "Estatutário Civil",
    categoria: "Profissionais da Educação",
    cargo: "Professor da Educação Básica",
    grupoEleitos: "",
    situacao: "EM_PROCESSAMENTO",
    mensagem: "Processamento em andamento.",
  },
  {
    id: 5005,
    execucaoId: 1001,
    matricula: "445567",
    vinculo: "1",
    nome: "ELISA MORAES PEREIRA",
    cpf: "222.333.444-55",
    orgao: "SEDUC",
    regimeJuridico: "Estatutário Civil",
    categoria: "Profissionais da Educação",
    cargo: "Professor da Educação Básica",
    grupoEleitos: "",
    situacao: "SUCESSO",
    mensagem: "Pessoa processada com sucesso.",
  },
];

const folhasPagamentoRubricaLogsMock: FolhaPagamentoRubricaLogRow[] = [
  {
    id: 7001,
    pessoaLogId: 5001,
    codigoRubrica: "1001",
    nomeRubrica: "SALÁRIO BÁSICO",
    tipoRubrica: "Provento",
    valorCalculado: "R$ 8.420,00",
    situacao: "CALCULADA",
    mensagem: "Rubrica calculada.",
  },
  {
    id: 7002,
    pessoaLogId: 5001,
    codigoRubrica: "1003",
    nomeRubrica: "DÉCIMO TERCEIRO",
    tipoRubrica: "Provento",
    valorCalculado: "R$ 701,66",
    situacao: "CALCULADA",
    mensagem: "Valor proporcional calculado.",
  },
  {
    id: 7003,
    pessoaLogId: 5002,
    codigoRubrica: "1002",
    nomeRubrica: "ADICIONAL NOTURNO",
    tipoRubrica: "Provento",
    valorCalculado: "R$ 312,40",
    situacao: "ALERTA",
    mensagem: "Divergência entre escala e apontamento.",
  },
  {
    id: 7004,
    pessoaLogId: 5003,
    codigoRubrica: "1002",
    nomeRubrica: "ADICIONAL NOTURNO",
    tipoRubrica: "Provento",
    valorCalculado: "R$ 0,00",
    situacao: "ERRO",
    mensagem: "Sem parametrização vigente.",
  },
  {
    id: 7005,
    pessoaLogId: 5005,
    codigoRubrica: "1001",
    nomeRubrica: "SALÁRIO BÁSICO",
    tipoRubrica: "Provento",
    valorCalculado: "R$ 5.860,00",
    situacao: "CALCULADA",
    mensagem: "Rubrica calculada.",
  },
];

export const folhaPagamentoMockRepository = {
  listarFolhas: (): FolhaPagamentoRow[] => structuredClone(folhasPagamentoMock),
  listarExecucoes: (): FolhaPagamentoExecucaoRow[] =>
    structuredClone(folhasPagamentoExecucoesMock),
  listarPessoaLogs: (): FolhaPagamentoPessoaLogRow[] =>
    structuredClone(folhasPagamentoPessoaLogsMock),
  listarRubricaLogs: (): FolhaPagamentoRubricaLogRow[] =>
    structuredClone(folhasPagamentoRubricaLogsMock),
};

export const folhaPagamentoService = {
  // TODO backend: GET /folhas-pagamento
  listarFolhas: folhaPagamentoMockRepository.listarFolhas,
  // TODO backend: GET /folhas-pagamento/{id}
  buscarFolhaPorId: (id: number) =>
    folhaPagamentoMockRepository
      .listarFolhas()
      .find((folha) => folha.id === id),
  // TODO backend: POST /folhas-pagamento
  criarFolha: (_request: CreateFolhaPagamentoRequest) => undefined,
  // TODO backend: PUT /folhas-pagamento/{id}
  atualizarFolha: (_id: number, _request: UpdateFolhaPagamentoRequest) =>
    undefined,
  // TODO backend: POST /folhas-pagamento/{id}/executar
  executarFolha: (_request: ExecutarFolhaPagamentoRequest) => undefined,
  // TODO backend: GET /folhas-pagamento/{id}/execucoes
  listarExecucoes: folhaPagamentoMockRepository.listarExecucoes,
  // TODO backend: GET /folhas-pagamento/execucoes/{execucaoId}/log
  listarPessoaLogs: folhaPagamentoMockRepository.listarPessoaLogs,
  // TODO backend: GET /folhas-pagamento/execucoes/{execucaoId}/log/{pessoaLogId}/rubricas
  listarRubricaLogs: folhaPagamentoMockRepository.listarRubricaLogs,
};
